//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimplomWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Complete_Products = new HashSet<Complete_Products>();
            this.Tiles = new HashSet<Tiles>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string contact_person { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
    
        public virtual ICollection<Complete_Products> Complete_Products { get; set; }
        public virtual ICollection<Tiles> Tiles { get; set; }
    }
}
